name: Build Docker Image

on:
  push:
    branches:
      - "master"

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: builder
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/obviyus/restic-db-docker:${{ github.sha }}
            ghcr.io/obviyus/restic-db-docker:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max